// Generated by Supabase AI CLI
// Universal Booking System Database Types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      admin_users: {
        Row: {
          id: string
          email: string
          password_hash: string
          name: string
          role: string
          tenant_id: string | null
          permissions: string[] | null
          is_active: boolean | null
          last_login: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          email: string
          password_hash: string
          name: string
          role?: string
          tenant_id?: string | null
          permissions?: string[] | null
          is_active?: boolean | null
          last_login?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          password_hash?: string
          name?: string
          role?: string
          tenant_id?: string | null
          permissions?: string[] | null
          is_active?: boolean | null
          last_login?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "admin_users_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          }
        ]
      }
      appointments: {
        Row: {
          appointment_data: Json | null
          cancellation_reason: string | null
          cancelled_at: string | null
          cancelled_by: string | null
          created_at: string | null
          currency: string | null
          customer_notes: string | null
          end_time: string
          external_event_id: string | null
          final_price: number | null
          id: string
          internal_notes: string | null
          professional_id: string | null
          quoted_price: number | null
          service_id: string | null
          start_time: string
          status: Database["public"]["Enums"]["appointment_status"] | null
          tenant_id: string
          timezone: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          appointment_data?: Json | null
          cancellation_reason?: string | null
          cancelled_at?: string | null
          cancelled_by?: string | null
          created_at?: string | null
          currency?: string | null
          customer_notes?: string | null
          end_time: string
          external_event_id?: string | null
          final_price?: number | null
          id?: string
          internal_notes?: string | null
          professional_id?: string | null
          quoted_price?: number | null
          service_id?: string | null
          start_time: string
          status?: Database["public"]["Enums"]["appointment_status"] | null
          tenant_id: string
          timezone?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          appointment_data?: Json | null
          cancellation_reason?: string | null
          cancelled_at?: string | null
          cancelled_by?: string | null
          created_at?: string | null
          currency?: string | null
          customer_notes?: string | null
          end_time?: string
          external_event_id?: string | null
          final_price?: number | null
          id?: string
          internal_notes?: string | null
          professional_id?: string | null
          quoted_price?: number | null
          service_id?: string | null
          start_time?: string
          status?: Database["public"]["Enums"]["appointment_status"] | null
          tenant_id?: string
          timezone?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "appointments_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      availability_templates: {
        Row: {
          created_at: string | null
          friday_slots: Json | null
          id: string
          is_default: boolean | null
          monday_slots: Json | null
          name: string
          saturday_slots: Json | null
          special_dates: Json | null
          sunday_slots: Json | null
          tenant_id: string | null
          thursday_slots: Json | null
          tuesday_slots: Json | null
          updated_at: string | null
          wednesday_slots: Json | null
        }
        Insert: {
          created_at?: string | null
          friday_slots?: Json | null
          id?: string
          is_default?: boolean | null
          monday_slots?: Json | null
          name: string
          saturday_slots?: Json | null
          special_dates?: Json | null
          sunday_slots?: Json | null
          tenant_id?: string | null
          thursday_slots?: Json | null
          tuesday_slots?: Json | null
          updated_at?: string | null
          wednesday_slots?: Json | null
        }
        Update: {
          created_at?: string | null
          friday_slots?: Json | null
          id?: string
          is_default?: boolean | null
          monday_slots?: Json | null
          name?: string
          saturday_slots?: Json | null
          special_dates?: Json | null
          sunday_slots?: Json | null
          tenant_id?: string | null
          thursday_slots?: Json | null
          tuesday_slots?: Json | null
          updated_at?: string | null
          wednesday_slots?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "availability_templates_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_history: {
        Row: {
          api_cost_usd: number | null
          confidence_score: number | null
          content: string
          conversation_context: Json | null
          conversation_outcome: string | null
          created_at: string | null
          id: string
          intent_detected: string | null
          is_from_user: boolean
          message_type: string
          model_used: string | null
          message_source: string | null
          processing_cost_usd: number | null
          tenant_id: string | null
          tokens_used: number | null
          user_id: string | null
        }
        Insert: {
          api_cost_usd?: number | null
          confidence_score?: number | null
          content: string
          conversation_context?: Json | null
          conversation_outcome?: string | null
          created_at?: string | null
          id?: string
          intent_detected?: string | null
          is_from_user: boolean
          message_type: string
          model_used?: string | null
          message_source?: string | null
          processing_cost_usd?: number | null
          tenant_id?: string | null
          tokens_used?: number | null
          user_id?: string | null
        }
        Update: {
          api_cost_usd?: number | null
          confidence_score?: number | null
          content?: string
          conversation_context?: Json | null
          conversation_outcome?: string | null
          created_at?: string | null
          id?: string
          intent_detected?: string | null
          is_from_user?: boolean
          message_type?: string
          model_used?: string | null
          message_source?: string | null
          processing_cost_usd?: number | null
          tenant_id?: string | null
          tokens_used?: number | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversation_history_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_history_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      service_categories: {
        Row: {
          created_at: string | null
          description: string | null
          display_order: number | null
          id: string
          name: string
          tenant_id: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          id?: string
          name: string
          tenant_id?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          display_order?: number | null
          id?: string
          name?: string
          tenant_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "service_categories_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      services: {
        Row: {
          advance_booking_days: number | null
          base_price: number | null
          category_id: string | null
          created_at: string | null
          currency: string | null
          description: string | null
          display_order: number | null
          duration_max: number | null
          duration_min: number | null
          duration_minutes: number | null
          duration_type: Database["public"]["Enums"]["duration_type"]
          id: string
          is_active: boolean | null
          max_bookings_per_day: number | null
          name: string
          price_model: Database["public"]["Enums"]["price_model"]
          service_config: Json | null
          tenant_id: string | null
          updated_at: string | null
        }
        Insert: {
          advance_booking_days?: number | null
          base_price?: number | null
          category_id?: string | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          display_order?: number | null
          duration_max?: number | null
          duration_min?: number | null
          duration_minutes?: number | null
          duration_type?: Database["public"]["Enums"]["duration_type"]
          id?: string
          is_active?: boolean | null
          max_bookings_per_day?: number | null
          name: string
          price_model?: Database["public"]["Enums"]["price_model"]
          service_config?: Json | null
          tenant_id?: string | null
          updated_at?: string | null
        }
        Update: {
          advance_booking_days?: number | null
          base_price?: number | null
          category_id?: string | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          display_order?: number | null
          duration_max?: number | null
          duration_min?: number | null
          duration_minutes?: number | null
          duration_type?: Database["public"]["Enums"]["duration_type"]
          id?: string
          is_active?: boolean | null
          max_bookings_per_day?: number | null
          name?: string
          price_model?: Database["public"]["Enums"]["price_model"]
          service_config?: Json | null
          tenant_id?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "services_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "service_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "services_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          ai_settings: Json
          business_address: Json | null
          business_description: string | null
          business_name: string
          business_rules: Json
          created_at: string | null
          domain: Database["public"]["Enums"]["business_domain"]
          domain_config: Json
          email: string
          id: string
          name: string
          phone: string
          slug: string
          status: string | null
          subscription_plan: string | null
          updated_at: string | null
          whatsapp_phone: string | null
        }
        Insert: {
          ai_settings?: Json
          business_address?: Json | null
          business_description?: string | null
          business_name: string
          business_rules?: Json
          created_at?: string | null
          domain: Database["public"]["Enums"]["business_domain"]
          domain_config?: Json
          email: string
          id?: string
          name: string
          phone: string
          slug: string
          status?: string | null
          subscription_plan?: string | null
          updated_at?: string | null
          whatsapp_phone?: string | null
        }
        Update: {
          ai_settings?: Json
          business_address?: Json | null
          business_description?: string | null
          business_name?: string
          business_rules?: Json
          created_at?: string | null
          domain?: Database["public"]["Enums"]["business_domain"]
          domain_config?: Json
          email?: string
          id?: string
          name?: string
          phone?: string
          slug?: string
          status?: string | null
          subscription_plan?: string | null
          updated_at?: string | null
          whatsapp_phone?: string | null
        }
        Relationships: []
      }
      user_tenants: {
        Row: {
          first_interaction: string | null
          last_interaction: string | null
          role: string | null
          tenant_id: string
          tenant_preferences: Json | null
          total_bookings: number | null
          user_id: string
        }
        Insert: {
          first_interaction?: string | null
          last_interaction?: string | null
          role?: string | null
          tenant_id: string
          tenant_preferences?: Json | null
          total_bookings?: number | null
          user_id: string
        }
        Update: {
          first_interaction?: string | null
          last_interaction?: string | null
          role?: string | null
          tenant_id?: string
          tenant_preferences?: Json | null
          total_bookings?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_tenants_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_tenants_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string | null
          email: string | null
          id: string
          name: string | null
          phone: string
          preferences: Json | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          email?: string | null
          id?: string
          name?: string | null
          phone: string
          preferences?: Json | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string | null
          id?: string
          name?: string | null
          phone?: string
          preferences?: Json | null
          updated_at?: string | null
        }
        Relationships: []
      }
      professionals: {
        Row: {
          id: string
          tenant_id: string
          name: string
          email: string | null
          phone: string | null
          specialties: string[] | null
          bio: string | null
          avatar_url: string | null
          is_active: boolean | null
          working_hours: Json | null
          google_calendar_credentials: Json | null
          google_calendar_id: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          email?: string | null
          phone?: string | null
          specialties?: string[] | null
          bio?: string | null
          avatar_url?: string | null
          is_active?: boolean | null
          working_hours?: Json | null
          google_calendar_credentials?: Json | null
          google_calendar_id?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          email?: string | null
          phone?: string | null
          specialties?: string[] | null
          bio?: string | null
          avatar_url?: string | null
          is_active?: boolean | null
          working_hours?: Json | null
          google_calendar_credentials?: Json | null
          google_calendar_id?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "professionals_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          }
        ]
      }
      subscription_payments: {
        Row: {
          id: string
          tenant_id: string | null
          payment_date: string | null
          payment_period_start: string | null
          payment_period_end: string | null
          amount: number | null
          currency: string | null
          subscription_plan: string | null
          payment_method: string | null
          payment_status: string | null
          stripe_payment_intent_id: string | null
          stripe_invoice_id: string | null
          payment_metadata: Json | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          tenant_id?: string | null
          payment_date?: string | null
          payment_period_start?: string | null
          payment_period_end?: string | null
          amount?: number | null
          currency?: string | null
          subscription_plan?: string | null
          payment_method?: string | null
          payment_status?: string | null
          stripe_payment_intent_id?: string | null
          stripe_invoice_id?: string | null
          payment_metadata?: Json | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string | null
          payment_date?: string | null
          payment_period_start?: string | null
          payment_period_end?: string | null
          amount?: number | null
          currency?: string | null
          subscription_plan?: string | null
          payment_method?: string | null
          payment_status?: string | null
          stripe_payment_intent_id?: string | null
          stripe_invoice_id?: string | null
          payment_metadata?: Json | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "subscription_payments_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          }
        ]
      }
      tenant_metrics: {
        Row: {
          id: string
          tenant_id: string | null
          metric_type: string
          metric_data: Json | null
          period: string
          calculated_at: string | null
          created_at: string | null
          updated_at: string | null
          metricas_validadas: Json | null
        }
        Insert: {
          id?: string
          tenant_id?: string | null
          metric_type: string
          metric_data?: Json | null
          period: string
          calculated_at?: string | null
          created_at?: string | null
          updated_at?: string | null
          metricas_validadas?: Json | null
        }
        Update: {
          id?: string
          tenant_id?: string | null
          metric_type?: string
          metric_data?: Json | null
          period?: string
          calculated_at?: string | null
          created_at?: string | null
          updated_at?: string | null
          metricas_validadas?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "tenant_metrics_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          }
        ]
      }
      platform_metrics: {
        Row: {
          id: string
          calculation_date: string
          period: string
          data_source: string | null
          comprehensive_metrics: Json | null
          participation_metrics: Json | null
          ranking_metrics: Json | null
          metricas_validadas: Json | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          calculation_date: string
          period: string
          data_source?: string | null
          comprehensive_metrics?: Json | null
          participation_metrics?: Json | null
          ranking_metrics?: Json | null
          metricas_validadas?: Json | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          calculation_date?: string
          period?: string
          data_source?: string | null
          comprehensive_metrics?: Json | null
          participation_metrics?: Json | null
          ranking_metrics?: Json | null
          metricas_validadas?: Json | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      ubs_metric_system_runs: {
        Row: {
          id: string
          run_date: string
          period_days: number
          run_status: string | null
          tenants_processed: number | null
          total_tenants: number | null
          execution_time_ms: number | null
          error_message: string | null
          metrics_calculated: number | null
          started_at: string | null
          completed_at: string | null
          data_quality_score: number | null
          missing_data_count: number | null
        }
        Insert: {
          id?: string
          run_date: string
          period_days: number
          run_status?: string | null
          tenants_processed?: number | null
          total_tenants?: number | null
          execution_time_ms?: number | null
          error_message?: string | null
          metrics_calculated?: number | null
          started_at?: string | null
          completed_at?: string | null
          data_quality_score?: number | null
          missing_data_count?: number | null
        }
        Update: {
          id?: string
          run_date?: string
          period_days?: number
          run_status?: string | null
          tenants_processed?: number | null
          total_tenants?: number | null
          execution_time_ms?: number | null
          error_message?: string | null
          metrics_calculated?: number | null
          started_at?: string | null
          completed_at?: string | null
          data_quality_score?: number | null
          missing_data_count?: number | null
        }
        Relationships: []
      }
      tenant_whatsapp_config: {
        Row: {
          tenant_id: string
          phone_number_id: string
          whatsapp_business_account_id: string | null
          webhook_url: string | null
          access_token: string | null
          webhook_verify_token: string | null
          is_active: boolean | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          tenant_id: string
          phone_number_id: string
          whatsapp_business_account_id?: string | null
          webhook_url?: string | null
          access_token?: string | null
          webhook_verify_token?: string | null
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          tenant_id?: string
          phone_number_id?: string
          whatsapp_business_account_id?: string | null
          webhook_url?: string | null
          access_token?: string | null
          webhook_verify_token?: string | null
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tenant_whatsapp_config_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          }
        ]
      }
      user_last_tenant: {
        Row: {
          phone_norm: string
          tenant_id: string
          last_seen_at: string
          created_at: string | null
        }
        Insert: {
          phone_norm: string
          tenant_id: string
          last_seen_at?: string
          created_at?: string | null
        }
        Update: {
          phone_norm?: string
          tenant_id?: string
          last_seen_at?: string
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "user_last_tenant_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          }
        ]
      }
      account_actions: {
        Row: {
          id: string
          source_platform: string | null
          lead_id: string | null
          username: string
          action_type: string
          post_id: string | null
          media_id: string | null
          comment_text: string | null
          dm_text: string | null
          executed_at: string | null
          execution_method: string | null
          success: boolean | null
          error_message: string | null
          retry_count: number | null
          daily_action_count: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          source_platform?: string | null
          lead_id?: string | null
          username: string
          action_type: string
          post_id?: string | null
          media_id?: string | null
          comment_text?: string | null
          dm_text?: string | null
          executed_at?: string | null
          execution_method?: string | null
          success?: boolean | null
          error_message?: string | null
          retry_count?: number | null
          daily_action_count?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          source_platform?: string | null
          lead_id?: string | null
          username?: string
          action_type?: string
          post_id?: string | null
          media_id?: string | null
          comment_text?: string | null
          dm_text?: string | null
          executed_at?: string | null
          execution_method?: string | null
          success?: boolean | null
          error_message?: string | null
          retry_count?: number | null
          daily_action_count?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "account_actions_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "instagram_leads"
            referencedColumns: ["id"]
          }
        ]
      }
      instagram_leads: {
        Row: {
          id: string
          username: string
          full_name: string | null
          bio: string | null
          followers_count: number | null
          following_count: number | null
          posts_count: number | null
          profile_pic_url: string | null
          is_business_account: boolean | null
          is_verified: boolean | null
          email: string | null
          phone: string | null
          website: string | null
          business_category: string | null
          search_term_id: string | null
          lead_score: number | null
          enrichment_status: string | null
          language: string | null
          country: string | null
          follow_status: string | null
          followed_at: string | null
          unfollowed_at: string | null
          follow_attempts: number | null
          last_follow_attempt_at: string | null
          last_interaction_type: string | null
          last_interaction_at: string | null
          interaction_count: number | null
          has_commented: boolean | null
          has_dm: boolean | null
          engagement_score: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          username: string
          full_name?: string | null
          bio?: string | null
          followers_count?: number | null
          following_count?: number | null
          posts_count?: number | null
          profile_pic_url?: string | null
          is_business_account?: boolean | null
          is_verified?: boolean | null
          email?: string | null
          phone?: string | null
          website?: string | null
          business_category?: string | null
          search_term_id?: string | null
          lead_score?: number | null
          enrichment_status?: string | null
          language?: string | null
          country?: string | null
          follow_status?: string | null
          followed_at?: string | null
          unfollowed_at?: string | null
          follow_attempts?: number | null
          last_follow_attempt_at?: string | null
          last_interaction_type?: string | null
          last_interaction_at?: string | null
          interaction_count?: number | null
          has_commented?: boolean | null
          has_dm?: boolean | null
          engagement_score?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          username?: string
          full_name?: string | null
          bio?: string | null
          followers_count?: number | null
          following_count?: number | null
          posts_count?: number | null
          profile_pic_url?: string | null
          is_business_account?: boolean | null
          is_verified?: boolean | null
          email?: string | null
          phone?: string | null
          website?: string | null
          business_category?: string | null
          search_term_id?: string | null
          lead_score?: number | null
          enrichment_status?: string | null
          language?: string | null
          country?: string | null
          follow_status?: string | null
          followed_at?: string | null
          unfollowed_at?: string | null
          follow_attempts?: number | null
          last_follow_attempt_at?: string | null
          last_interaction_type?: string | null
          last_interaction_at?: string | null
          interaction_count?: number | null
          has_commented?: boolean | null
          has_dm?: boolean | null
          engagement_score?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      instagram_interactions: {
        Row: {
          id: string
          lead_id: string | null
          instagram_user_id: string | null
          username: string
          interaction_type: string
          post_id: string | null
          media_id: string | null
          comment_text: string | null
          message_text: string | null
          interaction_timestamp: string
          detected_at: string | null
          auto_followed: boolean | null
          followed_at: string | null
          auto_replied: boolean | null
          replied_at: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          lead_id?: string | null
          instagram_user_id?: string | null
          username: string
          interaction_type: string
          post_id?: string | null
          media_id?: string | null
          comment_text?: string | null
          message_text?: string | null
          interaction_timestamp: string
          detected_at?: string | null
          auto_followed?: boolean | null
          followed_at?: string | null
          auto_replied?: boolean | null
          replied_at?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          lead_id?: string | null
          instagram_user_id?: string | null
          username?: string
          interaction_type?: string
          post_id?: string | null
          media_id?: string | null
          comment_text?: string | null
          message_text?: string | null
          interaction_timestamp?: string
          detected_at?: string | null
          auto_followed?: boolean | null
          followed_at?: string | null
          auto_replied?: boolean | null
          replied_at?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      account_actions_daily_stats: {
        Row: {
          action_date: string | null
          action_type: string | null
          execution_method: string | null
          total_actions: number | null
          successful_actions: number | null
          failed_actions: number | null
          avg_retries: number | null
        }
      }
      account_actions_today_count: {
        Row: {
          action_type: string | null
          count_today: number | null
          last_action_at: string | null
        }
      }
    }
    Functions: {
      citext: {
        Args: { "": boolean } | { "": string } | { "": unknown }
        Returns: string
      }
      citext_hash: {
        Args: { "": string }
        Returns: number
      }
      citextin: {
        Args: { "": unknown }
        Returns: string
      }
      citextout: {
        Args: { "": string }
        Returns: unknown
      }
      citextrecv: {
        Args: { "": unknown }
        Returns: string
      }
      citextsend: {
        Args: { "": string }
        Returns: string
      }
    }
    Enums: {
      appointment_status:
        | "pending"
        | "confirmed"
        | "in_progress"
        | "completed"
        | "cancelled"
        | "no_show"
        | "rescheduled"
      business_domain:
        | "legal"
        | "healthcare"
        | "education"
        | "beauty"
        | "sports"
        | "consulting"
        | "other"
      duration_type: "fixed" | "variable" | "estimated" | "session"
      price_model: "fixed" | "hourly" | "package" | "dynamic" | "consultation"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Constants for validation and reference
export const Constants = {
  public: {
    Enums: {
      appointment_status: [
        "pending",
        "confirmed",
        "in_progress", 
        "completed",
        "cancelled",
        "no_show",
        "rescheduled",
      ],
      business_domain: [
        "legal",
        "healthcare",
        "education",
        "beauty",
        "sports",
        "consulting",
        "other",
      ],
      duration_type: ["fixed", "variable", "estimated", "session"],
      price_model: ["fixed", "hourly", "package", "dynamic", "consultation"],
    },
  },
} as const 

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]

// Specific types for common usage
export type Tenant = Tables<'tenants'>
export type User = Tables<'users'>
export type Service = Tables<'services'>
export type Appointment = Tables<'appointments'>
export type ConversationHistory = Tables<'conversation_history'>
export type TenantMetrics = Tables<'tenant_metrics'>
export type PlatformMetrics = Tables<'platform_metrics'>
export type Professional = Tables<'professionals'>
export type SubscriptionPayment = Tables<'subscription_payments'>
export type AdminUser = Tables<'admin_users'>
export type UBSMetricSystemRuns = Tables<'ubs_metric_system_runs'>

export type BusinessDomain = Enums<'business_domain'>
export type AppointmentStatus = Enums<'appointment_status'>
export type DurationType = Enums<'duration_type'>
export type PriceModel = Enums<'price_model'>

// JSONB-based Platform Metrics Types
export interface PlatformComprehensiveMetrics {
  calculation_method?: string
  calculation_date?: string
  period?: string
  tenants_processed?: number
  total_tenants?: number
  platform_mrr?: number
  total_revenue?: number
  total_monthly_revenue?: number
  avg_revenue_per_tenant?: number
  revenue_platform_ratio?: number
  active_tenants?: number
  total_appointments?: number
  total_customers?: number
  total_chat_minutes?: number
  total_conversations?: number
  total_confirmed_appointments?: number
  total_cancelled_appointments?: number
  total_pending_appointments?: number
  total_completed_appointments?: number
  total_new_customers?: number
  total_returning_customers?: number
  customer_retention_rate_pct?: number
  average_business_health_score?: number
  average_risk_score?: number
  appointment_success_rate_pct?: number
  appointment_cancellation_rate_pct?: number
  appointment_completion_rate_pct?: number
  average_appointments_growth_rate?: number
  spam_rate_pct?: number
  operational_efficiency_pct?: number
  platform_avg_conversion_rate?: number
}

export interface PlatformParticipationMetrics {
  avg_appointments_platform_percentage?: number
  avg_customers_platform_percentage?: number
  avg_revenue_platform_percentage?: number
  revenue_usage_distortion_index?: number
  receita_uso_ratio?: number
  tenants_above_avg_usage?: number
  tenants_below_avg_usage?: number
  revenue_concentration_top_3?: number
}

export interface PlatformRankingMetrics {
  platform_health_score?: number
  operational_efficiency_pct?: number
  cancellation_rate_pct?: number
  top_revenue_tenants?: any[]
  top_appointment_tenants?: any[]
}

// Domain-specific configurations
export interface DomainConfig {
  // Legal
  specialties?: string[]
  consultation_types?: string[]
  requires_documents?: boolean
  preparation_time_minutes?: number
  
  // Healthcare  
  session_types?: string[]
  modalities?: string[]
  requires_intake?: boolean
  
  // Education
  subjects?: string[]
  levels?: string[]
  class_types?: string[]
  locations?: string[]
  
  // Beauty
  services_categories?: string[]
  professionals_count?: number
  accepts_walk_ins?: boolean
  combo_services?: boolean
  
  // Sports
  sports?: string[]
  equipment_provided?: boolean
  weather_dependent?: boolean
}

export interface AISettings {
  greeting_message: string
  domain_keywords: string[]
  escalation_triggers?: string[]
  sensitive_topics?: string[]
  crisis_response?: string
  upsell_enabled?: boolean
  motivational_messages?: boolean
}

export interface BusinessRules {
  working_hours: {
    monday: string[]
    tuesday: string[]
    wednesday: string[]
    thursday: string[]
    friday: string[]
    saturday: string[]
    sunday: string[]
  }
  advance_booking_days?: number
  cancellation_policy?: string
  payment_methods?: string[]
  travel_time_minutes?: number
  package_discounts?: boolean
  peak_hours_surcharge?: number
  loyalty_program?: boolean
  weather_cancellation?: boolean
  court_booking_required?: boolean
}

// Platform Metrics with JSONB structure support
export interface PlatformMetricsWithJsonb {
  id?: string
  calculation_date: string
  period: string
  data_source?: string | null
  comprehensive_metrics?: PlatformComprehensiveMetrics | Json
  participation_metrics?: PlatformParticipationMetrics | Json
  ranking_metrics?: PlatformRankingMetrics | Json
  metricas_validadas?: Json
  created_at?: string | null
  updated_at?: string | null
} 